# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\venv\src\design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 394)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(219, 102))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 591, 181))
        self.groupBox.setObjectName("groupBox")
        self.btnBrowse = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowse.setGeometry(QtCore.QRect(30, 90, 75, 23))
        self.btnBrowse.setObjectName("btnBrowse")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(200, 19, 81, 20))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 40, 231, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.axes2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.axes2.setContentsMargins(0, 0, 0, 0)
        self.axes2.setObjectName("axes2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(150, 40, 181, 131))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.axes1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.axes1.setContentsMargins(0, 0, 0, 0)
        self.axes1.setObjectName("axes1")
        self.btnShow = QtWidgets.QPushButton(self.groupBox)
        self.btnShow.setGeometry(QtCore.QRect(393, 16, 131, 23))
        self.btnShow.setObjectName("btnShow")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 591, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 131, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(340, 40, 231, 131))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.axes4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.axes4.setContentsMargins(0, 0, 0, 0)
        self.axes4.setObjectName("axes4")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(150, 40, 181, 131))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.axes3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.axes3.setContentsMargins(0, 0, 0, 0)
        self.axes3.setObjectName("axes3")
        self.btnShow2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnShow2.setGeometry(QtCore.QRect(393, 16, 131, 23))
        self.btnShow2.setObjectName("btnShow2")
        self.btn8 = QtWidgets.QRadioButton(self.groupBox_2)
        self.btn8.setGeometry(QtCore.QRect(30, 50, 82, 17))
        self.btn8.setObjectName("btn8")
        self.btn16 = QtWidgets.QRadioButton(self.groupBox_2)
        self.btn16.setGeometry(QtCore.QRect(30, 70, 82, 17))
        self.btn16.setObjectName("btn16")
        self.btn32 = QtWidgets.QRadioButton(self.groupBox_2)
        self.btn32.setGeometry(QtCore.QRect(30, 90, 82, 17))
        self.btn32.setObjectName("btn32")
        self.btn64 = QtWidgets.QRadioButton(self.groupBox_2)
        self.btn64.setGeometry(QtCore.QRect(30, 110, 82, 17))
        self.btn64.setObjectName("btn64")
        self.btn256 = QtWidgets.QRadioButton(self.groupBox_2)
        self.btn256.setGeometry(QtCore.QRect(30, 130, 82, 17))
        self.btn256.setChecked(True)
        self.btn256.setObjectName("btn256")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "test"))
        self.groupBox.setTitle(_translate("MainWindow", "Image originale"))
        self.btnBrowse.setText(_translate("MainWindow", "Parcourir"))
        self.label.setText(_translate("MainWindow", "Image Originale"))
        self.btnShow.setText(_translate("MainWindow", "Afficher Histogramme"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Reduction en niveaux de gris"))
        self.label_2.setText(_translate("MainWindow", "Image en niveaux de gris"))
        self.btnShow2.setText(_translate("MainWindow", "Afficher Histogramme"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn16.setText(_translate("MainWindow", "16"))
        self.btn32.setText(_translate("MainWindow", "32"))
        self.btn64.setText(_translate("MainWindow", "64"))
        self.btn256.setText(_translate("MainWindow", "default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

